spring.application.name=NationalDefenceManagementSystem

spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/national_defence_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT SPRING SEC
jwt.secret=${JWT_SECRET:PzGhmnPU8aSK58kK5KEKpRULpR+Y2BpkLlEF15zsdIU=}
jwt.expiration=604800000